[15:17:13] [Client thread/INFO]: Setting user: arhenniuss
[15:17:24] [Client thread/INFO]: LWJGL Version: 2.9.4
[15:17:46] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:ChatMod
[15:17:49] [Client thread/ERROR]: Couldn't initialize twitch stream
[15:17:49] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:17:50] [Thread-8/INFO]: Initializing LWJGL OpenAL
[15:17:50] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:17:53] [Thread-8/INFO]: OpenAL initialized.
[15:17:53] [Sound Library Loader/INFO]: Sound engine started
[15:18:15] [Client thread/INFO]: Created: 16x16 textures-atlas
[15:18:27] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:ChatMod
[15:18:28] [Client thread/INFO]: SoundSystem shutting down...
[15:18:28] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[15:18:28] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:18:28] [Thread-10/INFO]: Initializing LWJGL OpenAL
[15:18:28] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:18:29] [Thread-10/INFO]: OpenAL initialized.
[15:18:29] [Sound Library Loader/INFO]: Sound engine started
[15:18:42] [Client thread/INFO]: Created: 512x512 textures-atlas
[15:19:03] [Client thread/INFO]: Connecting to mc.fakepixel.fun, 25565
[15:19:07] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:07] [Client thread/INFO]: [CHAT] The inspection has begun, please don't move.
[15:19:15] [Client thread/INFO]: Connecting to mc.fakepixel.fun, 25565
[15:19:17] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:17] [Client thread/INFO]: [CHAT] The inspection has begun, please don't move. ยง7(2)
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:24] [Client thread/INFO]: [CHAT] To continue, enter the digits from ยงethe picture ยงfinto chat.
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:25] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 257
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at net.minecraft.world.chunk.Chunk.fillChunk(Chunk.java:1315) ~[Chunk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:757) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:63) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.play.server.S21PacketChunkData.processPacket(S21PacketChunkData.java:14) ~[S21PacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:42] [Client thread/INFO]: Connecting to mc.fakepixel.fun, 25565
[15:19:48] [Client thread/INFO]: Connecting to mc.fakepixel.fun, 25565
[15:19:54] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password>
[15:19:54] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:55] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(2)
[15:19:55] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(3)
[15:19:55] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(4)
[15:19:55] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(5)
[15:19:55] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(6)
[15:19:56] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(7)
[15:19:56] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:56] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:19:56] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(8)
[15:19:57] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(9)
[15:19:58] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(10)
[15:19:59] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(11)
[15:20:00] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(12)
[15:20:01] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(13)
[15:20:02] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:20:02] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(14)
[15:20:03] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:20:03] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(15)
[15:20:04] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(16)
[15:20:05] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(17)
[15:20:06] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(18)
[15:20:07] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:20:07] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(19)
[15:20:08] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(20)
[15:20:09] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(21)
[15:20:10] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:20:10] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(22)
[15:20:11] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(23)
[15:20:12] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(24)
[15:20:13] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:20:13] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(25)
[15:20:14] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(26)
[15:20:15] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(27)
[15:20:16] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(28)
[15:20:17] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(29)
[15:20:18] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(30)
[15:20:18] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:20:19] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(31)
[15:20:20] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(32)
[15:20:21] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(33)
[15:20:21] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
[15:20:22] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(34)
[15:20:23] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(35)
[15:20:24] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(36)
[15:20:25] [Client thread/INFO]: [CHAT] ยงeUse - ยงa/login <your password> ยง7(37)
[15:20:25] [Client thread/INFO]: [CHAT] ยงeYou successfully logged in
[15:20:25] [Client thread/INFO]: [CHAT] ยงeYou can connect account with discord!
[15:20:29] [Client thread/INFO]: [CHAT] >>> [MVP+] Namo_Gaming joined the lobby! <<<
[15:20:29] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยง2ยง2[GM] arhenniussยงe joined.
[15:20:29] [Client thread/INFO]: [CHAT] ยงeOnline Friends on Fakepixel:
 ยงeยงaยงa[VIP] toibul_ggยงe is playing on ยงesbdung-9
 ยงeยงbยงb[MVPยงc+ยงb] betaggยงe is playing on ยงeskyblock-1
 ยงeยง6ยง6[MVPยงc+ยงc+ยง6] _kurkure_ยงe is playing on ยงesbend-2
 ยงeยง2ยง2[GM] _suspected_ยงe is playing on ยงesbi-13
 ยงeยงdยงc[ALPHA] _classydinoยงe is playing on ยงesbdung-8
ยงe...and ยงe2 ยงemore...
[15:20:31] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงejoined.
[15:20:36] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[MOD] ayamorreยงf: ยงfSKILL LEVEL UP Fishing XXVโXXVI
[15:20:54] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงeleft.
[15:20:56] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงejoined. ยง7(2)
[15:20:58] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงeleft. ยง7(2)
[15:21:01] [Client thread/INFO]: [CHAT] [MVP] Benzy_Gamer joined the lobby!
[15:21:01] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงejoined. ยง7(3)
[15:22:01] [Client thread/INFO]: [CHAT] You are playing on profile: Grape
[15:22:01] [Client thread/INFO]: [CHAT] Darklord9601: wht give you
[15:22:01] [Client thread/INFO]: [CHAT] Welcome to Fakepixel SkyBlock!
[15:22:01] [Client thread/INFO]: [CHAT] 20% experience multiplier is currently enabled!
[15:22:01] [Client thread/INFO]: [CHAT] +10 Magic Find Bonus!
[15:22:01] [Client thread/INFO]: [CHAT] Saffisme: selling personal compactor at map for 500k
[15:22:01] [Client thread/INFO]: [CHAT] SayHi25: where you
[15:22:01] [Client thread/INFO]: [CHAT] aduf786786: selling frozen blaze armour no legging in cheap at map
[15:22:01] [Client thread/INFO]: [CHAT] [MVP] r42better: sell it
[15:22:02] [Client thread/INFO]: [CHAT] daeth: i want a minning pet
[15:22:02] [Client thread/INFO]: [CHAT] [MVP] r42better: they sell for some good money
[15:22:03] [Client thread/INFO]: [CHAT] Darklord9601: I dont have
[15:22:08] [Client thread/INFO]: [CHAT] SayHi25: visit me to visit my new super store
[15:22:14] [Client thread/INFO]: [CHAT] daeth: u give me also mooney
[15:22:20] [Client thread/INFO]: [CHAT] daeth: only 1m
[15:22:20] [Client thread/INFO]: [CHAT] Darklord9601: price
[15:22:24] [Client thread/INFO]: [CHAT] HOPPITY'S HUNT A Chocolate Lunch Egg has appeared!
[15:22:27] [Client thread/INFO]: [CHAT] ยงa[VIP] ยงaWhiteBilli089 ยงaยง7is ยง7friends ยง7with ยง7a ยง8[ยง7[Lvl 30] ยง6Horseยง8]
[15:22:30] [Client thread/INFO]: [CHAT] Darklord9601: bro 800k
[15:22:35] [Client thread/INFO]: [CHAT] [Skyblock] ahadparmar visited your island!
[15:22:36] [Client thread/INFO]: [CHAT] SayHi25: visit me to visit my new super store ยง7(2)
[15:22:37] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงdยงd[Sยงc+ยงd] yashgamer10101ยงe joined.
[15:22:40] [Client thread/INFO]: [CHAT] daeth: 900.5k
[15:22:48] [Client thread/INFO]: [CHAT] ยงaOnline Staff (ยงf1ยงa):
[15:22:48] [Client thread/INFO]: [CHAT] ยง7- ยงfยง2ยง2[MOD] ayamorre
[15:22:48] [Client thread/INFO]: [CHAT] ยงaVanished Staffยงf: ยง2ยง2[GM] arhenniussยงf, ยง2ยง2[GM] _suspected_
[15:22:51] [Client thread/INFO]: [CHAT] Darklord9601: bro pls 800k
[15:22:57] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงf_sus
[15:23:03] [Client thread/INFO]: [CHAT] Saffisme: selling personal compactor at map for 500k
[15:23:04] [Client thread/INFO]: [CHAT] HOPPITY'S HUNT You found a Chocolate Dinner Egg next to the Farmhouse!
[15:23:08] [Client thread/INFO]: [CHAT] daeth: no
[15:23:09] [Client thread/INFO]: [CHAT] ยง7Sandhu_001ยงa has sent you a trade request. ยงbClick hereยงa to accept!
[15:23:09] [Client thread/INFO]: [CHAT] HOPPITY'S HUNT You found Misty (COMMON)!
[15:23:09] [Client thread/INFO]: [CHAT] NEW RABBIT! +1 Chocolate and 0.002x Chocolate per second!
[15:23:14] [Client thread/INFO]: [CHAT] Darklord9601: pls 800k
[15:23:19] [Client thread/INFO]: [CHAT] 
ยง4[WATCHDOG ANNOUNCEMENT]
Watchdog has banned ยงcยงl191 player ยงrin the last 7 days.
Staff have banned an additional ยงcยงl458 players ยงrin the last 7 days.
ยงcBlacklisted modifications are a bannable offense!
          

[15:23:23] [Client thread/INFO]: [CHAT] ยงaPlayer ยง7ยง2ยง2[GM] _suspected_ ยงe(nicked as ยง7ยงb[MVP<plus>ยงb] Duooยงe) ยงais playing on ยงeskyblock-8ยงa.
[15:23:28] [Client thread/INFO]: [CHAT] Darklord9601: ok 850k
[15:23:32] [Client thread/INFO]: [CHAT] The /trade request from Sandhu_001 expired!
[15:23:34] [Client thread/INFO]: [CHAT] ramijsk: 443
[15:23:38] [Client thread/INFO]: [CHAT] Saffisme: k
[15:23:41] [Client thread/INFO]: [CHAT] Darklord9601: then
[15:23:59] [Client thread/INFO]: [CHAT] Sending to skyblock-8..
[15:24:20] [Client thread/INFO]: [CHAT] You are playing on profile: Grape
[15:24:20] [Client thread/INFO]: [CHAT] Welcome to Fakepixel SkyBlock!
[15:24:20] [Client thread/INFO]: [CHAT] 20% experience multiplier is currently enabled!
[15:24:20] [Client thread/INFO]: [CHAT] +10 Magic Find Bonus!
[15:24:20] [Client thread/INFO]: [CHAT] tzbeastboy: lemme turn my pc on after 1 hour
[15:24:25] [Client thread/INFO]: [CHAT] tzbeastboy: CZ of light;(
[15:24:42] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงeleft.
[15:24:44] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงejoined.
[15:24:48] [Client thread/INFO]: [CHAT] [MVP+] Namo_Gaming: sus
[15:24:49] [Client thread/INFO]: [CHAT] lol32313: selln snow minion /visit me
[15:24:58] [Client thread/INFO]: [CHAT] [MVP+] Namo_Gaming: _suspected_
[15:25:06] [Client thread/INFO]: [CHAT] Unknown player.
[15:25:07] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงfokay im going to steal the title of auto mod from arhenniuss bai
[15:25:17] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงeleft.
[15:25:18] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfsus
[15:25:20] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงejoined.
[15:25:20] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงf?
[15:25:25] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfcome to my is
[15:25:31] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfautmod?
[15:25:32] [Client thread/INFO]: [CHAT] ยงb[Skyblock] ยง7ยงb[MVPยง5+ยงb] Duoo ยงavisited your island!
[15:25:36] [Client thread/INFO]: [CHAT] Sending to sbi-6..
[15:25:55] [Client thread/INFO]: [CHAT] You are playing on profile: Grape
[15:25:55] [Client thread/INFO]: [CHAT] [MVP+] Duoo: demene
[15:25:55] [Client thread/INFO]: [CHAT] Welcome to Fakepixel SkyBlock!
[15:25:56] [Client thread/INFO]: [CHAT] 20% experience multiplier is currently enabled!
[15:25:56] [Client thread/INFO]: [CHAT] +10 Magic Find Bonus!
[15:25:56] [Client thread/INFO]: [CHAT] [MVP+] Duoo: fuck
[15:25:56] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] _suspected_ ยงcmuted ยงeยง2ยง2[GM] _suspected_ยงc!
ยงcDuration: ยงe4 hours
ยงcReason: ยงeMinor Chat Infraction
[15:25:56] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงeleft.
[15:25:56] [Client thread/INFO]: Warning: Clientside chunk ticking took 119 ms
[15:25:56] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงejoined.
[15:25:59] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงeleft. ยง7(2)
[15:26:00] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] _suspected_ ยงcunmuted ยงbยง2ยง2[GM] _suspected_ยงc!
[15:26:01] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVP] benzy_gamer ยงejoined. ยง7(2)
[15:26:03] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] arhenniuss ยงcmuted ยงeยง2ยง2[GM] _suspected_ยงc!
ยงcDuration: ยงe4 hours
ยงcReason: ยงeMinor Chat Infraction
[15:26:05] [Client thread/INFO]: [CHAT] Screenshot taken: IGN-Duoo Mute 4H Minor Chat Infraction+29092024_152605.png
[15:26:06] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงfsaw that?
[15:26:11] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงfunmute me breh
[15:26:44] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงfunmute me breh
[15:26:58] [Client thread/INFO]: [CHAT] ยงb[MVPยง5+ยงb] ยงbDuoo ยงbยง7is ยง7holding ยง8[ยงdWithered Hyperion ยง6โชโชโชโชโชยงcโธยง8]
[15:27:00] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[MOD] ayamorreยงf: ยงfu can do iturself too lmO
[15:27:08] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] arhenniuss ยงcunmuted ยงbยง2ยง2[GM] _suspected_ยงc!
[15:27:10] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงf..
[15:27:14] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfwait
[15:27:22] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงfonly the one who mued can unmute ayamommy
[15:27:23] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfi need to test my mod update
[15:27:28] [Client thread/INFO]: [CHAT] [MVP+] Duoo: gay
[15:27:30] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVPยงc+ยงb] betagg ยงeleft.
[15:27:33] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] arhenniuss ยงcmuted ยงeยง2ยง2[GM] _suspected_ยงc!
ยงcDuration: ยงe1 month 15 days
ยงcReason: ยงeMajor Chat Infraction
[15:27:35] [Client thread/INFO]: [CHAT] Screenshot taken: IGN-Duoo Mute 45D Major Chat Infraction+29092024_152735.png
[15:27:35] [Client thread/INFO]: [CHAT] ยงaFriend > ยงbยงb[MVPยงc+ยงb] betagg ยงejoined.
[15:27:49] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงfUNMUTE ME
[15:28:07] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] arhenniuss ยงcunmuted ยงbยง2ยง2[GM] _suspected_ยงc!
[15:28:11] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfbruhh
[15:28:18] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfsome code iisue
[15:28:19] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] _suspected_ ยงcmuted ยงeยง2ยง2[GM] _suspected_ยงc!
ยงcDuration: ยงe1 month 15 days
ยงcReason: ยงeMajor Chat Infraction
[15:28:23] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfcya sppm
[15:28:26] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงeยง2ยง2[GM] _suspected_ ยงcunmuted ยงbยง2ยง2[GM] _suspected_ยงc!
[15:28:29] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] _suspected_ยงf: ยงfbreh..
[15:28:30] [Client thread/INFO]: [CHAT] ยงb[STAFF] ยงfยงfยง2ยง2[GM] arhenniussยงf: ยงfcya soon
[15:28:32] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_421]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.network.play.server.S14PacketEntity.getEntity(S14PacketEntity.java:64) ~[S14PacketEntity.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleEntityMovement(NetHandlerPlayClient.java:609) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S14PacketEntity.processPacket(S14PacketEntity.java:53) ~[S14PacketEntity.class:?]
	at net.minecraft.network.play.server.S14PacketEntity$S15PacketEntityRelMove.processPacket(S14PacketEntity.java:109) ~[S14PacketEntity$S15PacketEntityRelMove.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_421]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_421]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 15 more
